services:
  mkdocs:
    image: notes-mkdocs
    volumes:
      - type: bind
        source: ./
        target: /docs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    develop:
      watch:
        - action: rebuild
          path: requirements.txt
